version: "3.8"

services:
  # Your existing backend with custom heavy libraries
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    container_name: pdfpage-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/pdfpage
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/temp:/app/temp
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "4.0"
    shm_size: 4gb

  # Fast PDF processing service (downloaded image)
  pdf-service:
    image: gotenberg/gotenberg:7
    container_name: pdfpage-pdf-service
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"

  # Fast image processing service (downloaded image)
  image-service:
    image: h2non/imaginary
    container_name: pdfpage-image-service
    ports:
      - "3002:9000"
    command: >
      -enable-url-source
      -mount /tmp
    volumes:
      - ./backend/temp:/tmp
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  # OCR processing service (downloaded image)
  ocr-service:
    image: jbarlow83/ocrmypdf
    container_name: pdfpage-ocr-service
    volumes:
      - ./backend/temp:/tmp
      - ./backend/uploads:/uploads
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "2.0"

  # Video processing service (downloaded image)
  video-service:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: pdfpage-video-service
    volumes:
      - ./backend/temp:/tmp
      - ./backend/uploads:/uploads
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"

  # LibreOffice document conversion (downloaded image)
  office-service:
    image: collabora/code
    container_name: pdfpage-office-service
    ports:
      - "3003:9980"
    environment:
      - domain=localhost
      - DONT_GEN_SSL_CERT=true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"

  # MongoDB
  mongo:
    image: mongo:7
    container_name: pdfpage-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    name: pdfpage-network
